### ISSUE TITLE
Intu dashboard won't show up on Pepper's tablet

### ISSUE THREAD

**Issue by takaomoriyama** [watson-intu/self#11]
When starting Intu on Pepper, nothing is shown on the Pepper's tablet on his breast.

**Comment by takaomoriyama** [comment]
When Intu is started, http://localhost:9443/www/dashboard#/ is passed to Browser service so that Intu dashboard is shown on the local web browser.
However, since Pepper's tablet is a Web browser running on Android, which is independent of Pepper, http://localhost does not connect to the Web server running on Intu on Pepper.

The proposed solution is to map "localhost" in URL into "198.18.0.1" which is Pepper's end-point address of the point-to-point network on USB connection between Pepper and Android (PR https://github.com/watson-intu/self-plugins/pull/1)
Note: This solution assumes https://github.com/watson-intu/self/pull/10 is available.

**Comment by takaomoriyama** [comment]
Added one more commit, which prevent periodical display of Logo on Pepper's tablet which might stop showing Intu dashboard, to PR https://github.com/watson-intu/self-plugins/pull/1. Please volunteer to review this.

![img_8206](https://user-images.githubusercontent.com/17893359/28364371-2d524af8-6cbf-11e7-9b5d-c47a9170efc1.JPG)

**Comment by rlyle** [comment]
AWESOME!

**Comment by takaomoriyama** [comment]
Richard,

The patch has been merged into self-plugins sub-module, but self repository is still pointing to old copy of self-plugins (and self-javascript-sdk also . How can I create a PR to fix this ?

The following commits are not referred to  by self repository.

self-plugins:
```
commit b49a955a7aa7ea92dd4937dbadbecd1844f7e6ca
Merge: bcca080 7db192c
Author: Richard Lyle <rlyle@palestar.com>
Date:   Fri Aug 4 10:05:38 2017 -0500

    Merge pull request #2 from takaomoriyama/self-issue11
    
    Show Intu dashboard on Pepper's tablet

commit 7db192cef0778fe940089b26a4e699c9fe1672dc
Merge: a96de3a bcca080
Author: Takao Moriyama <moriyama@jp.ibm.com>
Date:   Mon Jul 31 14:33:43 2017 +0900

    Merge remote-tracking branch 'upstream/develop' into self-issue11

commit a96de3a5766da81926bc1bd71f7a631b123a4043
Author: Takao Moriyama <moriyama@jp.ibm.com>
Date:   Wed Jul 19 20:07:13 2017 +0900

    Add mechanism to avoid periodical display of logo which might stop
    showing Intu dashboard on Pepper's tablet.

commit bcca080a5f6e7e8f2523649364490b771cbbeffd
Author: Hide Muta <hide.muta@au1.ibm.com>
Date:   Mon Jul 10 12:52:53 2017 +0800

    Clustring based object detector

commit 771bc9da0d85613a0b15bfc83aa91f64709df32c
Author: Takao Moriyama <moriyama@jp.ibm.com>
Date:   Tue Jul 4 18:36:40 2017 +0900

    Map "localhost" in URL to "198.18.0.1" to display Pepper's web contents (e.g. dashboard) on the tablet

```

self-javascript-sdk:
```
commit c5150654f87fcc4f2783b99e9e07d769c66a88c0
Merge: 087213b c0e921c
Author: Richard Lyle <rlyle@palestar.com>
Date:   Fri Jul 14 20:25:34 2017 -0500

    Merge pull request #1 from mhew49680/develop
    
    Fixed Typos

commit c0e921ca76ced316d89fdee4dfea38a1fd8f7008
Author: Mary Hewitt <mary.hewitt@woodside.com.au>
Date:   Thu Jul 13 13:28:42 2017 +0800

    capitalised Thing.js

commit 93ff38b0925237882cf34913d77a70bd85ca2354
Author: Mary Hewitt <mary.hewitt@woodside.com.au>
Date:   Thu Jul 13 13:27:11 2017 +0800

    first step, fix typo in unsubscribe function name in blackboard.js; rename thing.js so it can be capitalised in next commit

```

**Comment by takaomoriyama** [comment]
The fix in self-plugins is not referred to by self main module. PR https://github.com/watson-intu/self/pull/30 is created.

**Comment by takaomoriyama** [comment]
Now necessary changes in plugins/ have been enabled by https://github.com/watson-intu/self/pull/30
