### ISSUE TITLE
Build errors on RHEL and Raspberian

### ISSUE THREAD

**Issue by scottdangelo** [watson-intu/self#22]
I'm unable to build intu on RHEL linux:
scottda [2:02 PM] 
[scott@oc0486027055 scripts]$ ./build_linux.sh 
Toolchain linux
No feed
No packages

Current build worktree: /home/scott/Intu/self
[ERROR]: Exception No such build config: linux

I get a similar issue on Raspberian:

**Comment by rlyle** [comment]
Ok, this should be fixed now, pull latest develop and try again..

**Comment by scottdangelo** [comment]
After pulling latest develop I still get the same failure.

**Comment by scottdangelo** [comment]
This actually does fix the issue. I had neglected to ./clean.sh
