### ISSUE TITLE
No Access to Intus Gateway

### ISSUE THREAD

**Issue by hlb1986** [watson-intu/self#29]
Hi there,

we are trying to login to intu gateway but we are not getting forward. The login freezes and there is no connection to intu. Any idea what might be the issue?

<img width="442" alt="bildschirmfoto 2017-08-25 um 19 37 31" src="https://user-images.githubusercontent.com/31354749/29725569-dd7c7186-89cc-11e7-8bc4-7b2a0e1249e9.png">

**Comment by gradybooch** [comment]
The gateway has been deprecated and intu is now fully open source

If you email me directly I can add you to our slack channel and give you an URL to the repository

**Comment by hlb1986** [comment]
thank you very much for the quick response. I sent you an email.
