### ISSUE TITLE
Mac OSX RC5 /  master / develop install: Could NOT find JSONCPP

### ISSUE THREAD

**Issue by agrosven** [watson-intu/self#3]
I'm trying to install the update just posted on Mac OSX.  This problem has been reproduced on both Yosemite and El Capitan

I've tried building: self-master, self-RC5, and self-develop

In each case, build fails with the error message:
  [ERROR]: ConfigureFailed Error occurred when configuring project self
...
and seems to be due to the error:
  Could NOT find JSONCPP (missing: JSONCPP_LIBRARIES JSONCPP_INCLUDE_DIRS)

**Comment by rlyle** [comment]
You didn't pull down the sub-modules as well.
