### ISSUE TITLE
Installing Intu on Raspberry Pi, causes the Pi to become stuck at 18%

### ISSUE THREAD

**Issue by livin1989** [watson-intu/self#33]
![screenshot from 2017-09-13 13 08 04](https://user-images.githubusercontent.com/23608882/30374339-e6ef0c58-9884-11e7-9889-9b25d30304c2.png)

**Comment by takaomoriyama** [comment]
Closing this issue because it no longer occurs after eliminating PCL plugins https://github.com/watson-intu/self/pull/26.
