### ISSUE TITLE
self_instance crashed

### ISSUE THREAD

**Issue by nddao** [watson-intu/self#42]
Trying SELF on Raspberry, got several issues, From the SelfInstance.log:
[10/28/17 11:51:11.059][STAT][SensorManager] Added sensor Health, Id: c97b37dd-9f83-0107-f51e-f71aa153ae61
[10/28/17 11:51:11.059][STAT][SensorManager] Added sensor Camera, Id: 6b8c89d5-b143-8c45-52b9-69ecf82ba0c1
[10/28/17 11:51:11.059][STAT][SensorManager] Added sensor DepthCamera, Id: a6d89e45-5ba0-4d50-be44-6b5f9719c002
[10/28/17 11:51:11.059][STAT][SensorManager] Added sensor Microphone, Id: a549d757-8c63-9cde-1c05-cb15306bd6d7
[10/28/17 11:51:11.059][STAT][SensorManager] Added sensor Network, Id: 43751c9e-1569-efd3-ad5a-324473f24619

1)  [WARN][OpenCVCamera] Failed to open camera. This Raspberry has a camera, and it has been tested. But some how SELF can not open camera.
2) ERRO][Network] OnTimeout() http://www.ibm.com
   [ERRO][Network] OnTimeout() http://www.google.com

WIFI is up and running, and others Watson services are up and running.

3) After a while, self_instance crashed , after ¨throwing an instance of 'Json::LogicError';   what():  Type is not convertible to string

[10/28/17 11:50:16.101][STAT][Conversation] ----- Recognized Text: are you  (0.697/0.460636), Language: en-US, TextId: 0x12e23b0
[10/28/17 11:50:16.769][STAT][Conversation] ---- Intent class RequestIntent Created, intent: ChitChat, confidence: 0.87 / 0.7, text: are you, TextId: 0x12e23b0
terminate called after throwing an instance of 'Json::LogicError'
  what():  Type is not convertible to string
./run_self.sh: line 80: 12521 Aborted                 (core dumped) ./self_instance -P ${PLATFORM} "$@"

Any setting to get further debug information?

**Comment by nddao** [comment]
[10/29/17 11:29:42.686][STAT][Conversation] ----- Recognized Text: what is IBM  (0.867/0.446217), Language: en-US, TextId: 0x16fa6f0
[10/29/17 11:29:43.404][STAT][Conversation] ---- Intent class RequestIntent Created, intent: culture, confidence: 1 / 0.7, text: what is IBM, TextId: 0x16fa6f0
terminate called after throwing an instance of 'Json::LogicError'
  what():  Type is not convertible to string
./run_self.sh: line 80:  1023 Aborted                 (core dumped) ./self_instance -P ${PLATFORM} "$@"

**Comment by nddao** [comment]
#6  0x761e8bdc in Json::throwLogicError (msg="Type is not convertible to string") at /home/pi/self/lib/cpp-sdk/lib/jsoncpp/jsoncpp.cpp:2412
No locals.
#7  0x761ea7b0 in Json::Value::asString[abi:cxx11]() const (this=0x1700df0) at /home/pi/self/lib/cpp-sdk/lib/jsoncpp/jsoncpp.cpp:2857
        oss = <incomplete type>
#8  0x76ce5408 in TextClassifier::ClassifyText::OnClassifyDone (this=0x14efe00) at /home/pi/self/src/classifiers/TextClassifier.cpp:422
        dialogNode = <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>
        dialogStack = {static nullRef = @0x762a22f8, static minLargestInt = -9223372036854775808, static maxLargestInt = 9223372036854775807, static maxLargestUInt = 18446744073709551615, static minInt = -2147483648, static maxInt = 2147483647, static maxUInt = 4294967295, static minInt64 = -9223372036854775808, static maxInt64 = 9223372036854775807, static maxUInt64 = 18446744073709551615, value_ = {int_ = 9149626847111156704, uint_ = 9149626847111156704, real_ = 4.4582396890280256e+303, bool_ = 224, string_ = 0x17013e0 "\304g\220u", map_ = 0x17013e0}, type_ = Json::arrayValue, allocated_ = 0, comments_ = 0x0}
        pIntent = 0x16ef200
        pTopResult = 0x16ee7d8
#9  0x76ce4ce0 in TextClassifier::ClassifyText::OnTextClassified (this=0x14efe00, a_Result=0x16f6660) at /home/pi/self/src/classifiers/TextClassifier.cpp:327
No locals.
#10 0x76ce9058 in Delegate<ITextClassifierProxy::ClassifyResult*>::method_stub<TextClassifier::ClassifyText, &TextClassifier::ClassifyText::OnTextClassified> (object_ptr=0x14efe00, weak_ptr=..., a1=0x16f6660) at /home/pi/self/lib/cpp-sdk/src/utils/Delegate.h:148
        p = 0x14efe00
#11 0x63fbb398 in Delegate<ITextClassifierProxy::ClassifyResult*>::operator() (this=0x17061e8, a1=0x16f6660) at /home/pi/self/lib/cpp-sdk/src/utils/Delegate.h:95
No locals.
#12 0x63fb93f0 in ConversationProxy::Request::OnTextClassified (this=0x17061d8, a_pResponse=0x16f6c80) at /home/pi/self/plugins/watson/services/Conversation/ConversationProxy.cpp:291
        pResult = 0x16f6660
#13 0x63fbbf70 in Delegate<ConversationResponse*>::method_stub<ConversationProxy::Request, &ConversationProxy::Request::OnTextClassified> (object_ptr=0x17061d8, weak_ptr=..., a1=0x16f6c80) at /home/pi/self/lib/cpp-sdk/src/utils/Delegate.h:148
        p = 0x17061d8
#14 0x63fb20d4 in Delegate<ConversationResponse*>::operator() (this=0x1510914, a1=0x16f6c80) at /home/pi/self/lib/cpp-sdk/src/utils/Delegate.h:95
No locals.
#15 0x63fb0648 in Conversation::MessageReq::OnResponse (this=0x15108f8, a_pResponse=0x16f6c80) at /home/pi/self/plugins/watson/services/Conversation/Conversation.cpp:204
No locals.
#16 0x63fb3060 in Delegate<ConversationResponse*>::method_stub<Conversation::MessageReq, &Conversation::MessageReq::OnResponse> (object_ptr=0x15108f8, weak_ptr=..., a1=0x16f6c80) at /home/pi/self/lib/cpp-sdk/src/utils/Delegate.h:148
        p = 0x15108f8
#17 0x63fb20d4 in Delegate<ConversationResponse*>::operator() (this=0x14c6ce8, a1=0x16f6c80) at /home/pi/self/lib/cpp-sdk/src/utils/Delegate.h:95
No locals.
#18 0x63fb32ac in IService::RequestObj<ConversationResponse>::OnResponse (this=0x14c6c40, a_pRequest=0x14c6c40) at /home/pi/self/lib/cpp-sdk/src/utils/IService.h:403
        startTime = 1509301783.348
        elapsed = 4.4895218401863848e-209
        pObject = 0x16f6c80

**Comment by rlyle** [comment]
I pushed a fix to stop this crash, but I'm afraid they went off and changed the dialog service which may have broken our sticky conversation code.
