### ISSUE TITLE
The speaking Dialog always says "I do not know how to "#intent" even thought Watson conversation returns correct response ( Test on Raspberry )

### ISSUE THREAD

**Issue by nddao** [watson-intu/self#44]
<Raspberry test> After configuring the bootstrap.json, I am able to connect to Watson services. However, I always get back from speaker the string " I do not know how to '#intent'.  Also from the Dash board, the WatsonRequestIntent shows  the string "I do not know how to [#intent name]
Clicking the [Advance] link to get the json file, look like the Conversation service returns correctly, but some how Intu does not interpret /parse correctly.
Here is from the log:
[STAT][Conversation] ----- Recognized Text: good afternoon  (0.996/0.458904), Language: en-US, TextId: 0x788cc0
[STAT][Conversation] ---- Intent class RequestIntent Created, intent: Greeting, confidence: 1 / 0.7, text: thank you, TextId: 0x788cc0
[STAT][RequestAgent] Adding request goal Greeting with 
[STAT][Conversation] Speaking Dialog: I do not know how to Greeting., TextId: 0x788cc0

Here is the question on dashboard:
MeText [Advanced]
good afternoon

And the reply on dashboard:

WatsonRequestIntent [Advanced]
I do not know how to Greeting.
#Greeting

Here is the Json file  getting from [Advanced]
{
  "GUID_": "182ddcab-8305-85ff-56c9-7c0176f2292e",
  "Type_": "RequestIntent",
  "m_Children": [
    {
      "GUID_": "2706a2ab-0b27-aa61-f027-6267198b9529",
      "Type_": "Goal",
      "m_Children": [
        {
          "GUID_": "37dae8f8-a32b-32ab-294a-ad5259d6800a",
          "Type_": "Say",
          "m_CreateTime": 1510087821.064,
          "m_State": "PROCESSING",
          "m_Text": "I do not know how to Greeting.",
          "m_eCategory": 1,
          "m_fImportance": 1,
          "m_fLifeSpan": 3600
        }
      ],
      "m_CreateTime": 1510087821.059,
      "m_DataType": "ADDED",
      "m_Name": "Greeting",
      "m_Params": {
        "Type_": "ParamsMap",
        "intent": "request",
        "skill": "Greeting",
        "target": "",
        "verb": "Greeting"
      },
      "m_State": "FAILED",
      "m_Text": "",
      "m_eCategory": 1,
      "m_fImportance": 1,
      "m_fLifeSpan": 3600
    }
  ],
  "m_Confidence": 1,
  "m_CreateTime": 1510087821.058,
  "m_Intent": {
    "confidence": 1,
    "conversation": {
      "context": {
        "conversation_id": "0d096409-ed41-47eb-aef6-6d9f3e15fabe",
        "m_EmotionalState": 0.6000000238418579,
        "m_Objects": null,
        "m_PreviousIntent": "",
        "system": {
          "_node_output_map": {
            "Welcome": [
              0
            ]
          },
          "dialog_request_counter": 1,
          "dialog_stack": [
            {
              "dialog_node": "Welcome"
            }
          ],
          "dialog_turn_counter": 1
        }
      },
      "entities": [
        {
          "entity": "sys-time",
          "value": "18:00:00"
        }
      ],
      "intents": [
        {
          "confidence": 1,
          "intent": "Greeting"
        }
      ],
      "output": {
        "text": [
          "Hi! I'm Pepper! I am here to point you in the right direction. You can ask me just about anything related IBM! You can ask me things like, \"What is DB2?\", \"Where is the executive briefing center?\", \"What is machine learning?\" and more!"
        ]
      }
    },
    "goal_params": {
      "answer": {
        "response": [
          "Hi! I'm Pepper! I am here to point you in the right direction. You can ask me just about anything related IBM! You can ask me things like, \"What is DB2?\", \"Where is the executive briefing center?\", \"What is machine learning?\" and more!"
        ]
      },
      "question": {
        "m_Children": [
          {
            "GUID_": "6a015a69-f87d-0aa9-8f12-f6de4839d591",
            "Type_": "IThing",
            "m_CreateTime": 1510087820.503,
            "m_DataType": "CacheMiss",
            "m_State": "ADDED",
            "m_eCategory": 0,
            "m_fImportance": 1,
            "m_fLifeSpan": 3600
          },
          {
            "GUID_": "b7ef6b61-6060-b272-6d93-5629d97c5144",
            "Type_": "IThing",
            "m_CreateTime": 1510087820.506,
            "m_DataType": "CacheMiss",
            "m_State": "ADDED",
            "m_eCategory": 0,
            "m_fImportance": 1,
            "m_fLifeSpan": 3600
          }
        ],
        "m_ClassifyIntent": true,
        "m_CreateTime": 1510087820.497,
        "m_Language": "en-US",
        "m_LocalDialog": false,
        "m_State": "ADDED",
        "m_Text": "good afternoon",
        "m_eCategory": 0,
        "m_fConfidence": 0.927,
        "m_fImportance": 1,
        "m_fLifeSpan": 3600
      }
    },
    "text": "good afternoon",
    "top_class": "Greeting"
  },
  "m_Parse": null,
  "m_ProxyID": "10e1f725-7809-73e4-ad78-3fbbdefa2af7",
  "m_Requests": [
    {
      "m_Target": "",
      "m_Verb": "Greeting"
    }
  ],
  "m_State": "ADDED",
  "m_Tags": null,
  "m_Text": "good afternoon",
  "m_Type": "linear",
  "m_eCategory": 1,
  "m_fImportance": 1,
  "m_fLifeSpan": 3600,
  "$$hashKey": "object:14"
}
![intu_dashboard](https://user-images.githubusercontent.com/31354746/32518937-f2072eca-c3bf-11e7-8ea9-a20fde553687.jpg)

**Comment by takaomoriyama** [comment]
Probably you are not using the version of Watson Conversation workspace which is included in the Intu code at etc/shared/intu_conversation_v1.json.
Could you create your own workspace instance based on intu_conversation_v1.json ? There is a guide at https://github.com/watson-intu/self#configuring-bluemix.

**Comment by nddao** [comment]
I do not use the version of Watson Conversation workspace which is included in the IntuWell,  but use my bluemix workspace. I went through those steps already, but did not change anything in the "m_IntentClasses"  and got those message in my screenshoot.
Is there any rule to construct the m_IntentClasses. Should m_Class must be the same as the Intent name in Bluemix conversation? 

On your sample screenshoot there is  #dialog below the reply. On the other hand, on my set up ( on Raspberry) it shows the name of an intent on Bluemix conversation.  What are the configuration I need to change in the bootstrap.json?

**Comment by nddao** [comment]
Found the problem. The Text_Classifier need to be modified so it can catches the intents of the Watson workspace.

**Comment by takaomoriyama** [comment]
Yes.
Every intent generated by Text Classifier proxies (IBM Watson Conversation for example) must fall into one of the intent classes defined in "m_IntentClasses" entry in the bootstrap.json file.
Ordinary questions are recognized by Watson Conversation as "dialog" intent, which matches to the following mapping entry.
```
            {                                                                                                                                                                                          
               "m_Class" : "QuestionIntent",                                                                                                                                                           
               "m_Intent" : "dialog*"                                                                                                                                                                  
            }, 
```
Then a QuestionIntent object is placed on the blackboard by Text Classifier.

If you create your own intent class, you need an entry the intent classes map in bootstrap.json, and to create appropriate agent to handle such new intent.
