### ISSUE TITLE
Support for Identity and Access Management (IAM)

### ISSUE THREAD

**Issue by daiki-kimura** [watson-intu/self#47]
IBM announced to all Watson users that migration of all Watson services to IAM was required by October 30, 2019

I think we might need to change around these files and related files.
https://github.com/watson-intu/cpp-sdk/blob/develop/src/utils/ServiceConfig.h
https://github.com/watson-intu/cpp-sdk/blob/develop/src/utils/IService.cpp

Or we might need to change for each service.
https://github.com/watson-intu/self-plugins/tree/develop/watson/services

**Comment by gradybooch** [comment]
Agreed.

Who here is still actively using Intu?

**Comment by daiki-kimura** [comment]
Thank you.

We are having an active Intu demo with Pepper-robot in THINK Lab at Tokyo.
And we (with @takaomoriyama) are trying to tackle this issue.
If anyone already tried to solve this issue, please comment at here

**Comment by takaomoriyama** [comment]
I reviewed documentation of IAM, and found that we don't need to change any of Intu code.

**Comment by daiki-kimura** [comment]
Thank you. I understand and verify your steps.
I'm gonna test on Pepper during next week about this. 

And I feel it is better to rename the `m_Password` to `m_ApiKey` , remove the `m_User` fields for future users, and modify the related parts.

**Comment by takaomoriyama** [comment]
Ya. Renaming m_Password to m_ApiKey make sense.
Please let me know when you confirm on your Pepper. Then I would start working on it.
